### ISSUE TITLE
java.lang.NoSuchMethodError: scala.collection.immutable.ListSet$.empty()Lscala/collection/immutable/ListSet;

### ISSUE THREAD

**Issue by rschiavi** [yieldbot/flambo#104]
was just trying run a basic Spark SQL (from the tests) and getting this

java.lang.NoSuchMethodError: scala.collection.immutable.ListSet$.empty()Lscala/collection/immutable/ListSet;

code the same as from the test:

```
(defn m []
  (let [conf (-> (conf/spark-conf)
                 (conf/master "local[*]")
                 (conf/app-name "sql-test"))]
    (sql/with-sql-context c conf
      (let [sc (sql/spark-context c)
            test-data ["{\"col1\":4,\"col2\":\"a\"}" "{\"col1\":6,\"col2\":\"a\"}" "{\"col1\":5,\"col2\":\"b\"}"]
            test-df (sql/json-rdd c (f/parallelize sc test-data))
            test-data-2 ["{\"col1\":4,\"col2\":\"a\"}" "{\"col1\":4,\"col2\":\"a\"}" "{\"col1\":6,\"col2\":\"a\"}"]
            test-df-2 (sql/json-rdd c (f/parallelize sc test-data-2))
            _ (sql/register-data-frame-as-table c test-df "foo")
            _ (sql/register-data-frame-as-table c test-df-2 "bar")]
        (println (f/count (sql/sql c "SELECT * FROM foo WHERE col2 = 'a'")))))))
```

**Comment by sorenmacbeth** [comment]
can you post your `project.clj` please?

**Comment by sorenmacbeth** [comment]
I'm not able to reproduce the error locally. My first guess would be to check the version of scala that your pulling in and make sure it's 2.11, then try doing a `lein clean` if you haven't recently and restart your repl.

**Comment by sorenmacbeth** [comment]
any updates here? I'd like to close this since I can't reproduce it.

**Comment by rschiavi** [comment]
had to do a lein clean, then install a different version of scala. that fixed it.
