### ISSUE TITLE
Warning killing my CI

### ISSUE THREAD

**Issue by cigrainger** [yieldbot/flambo#118]
Any time I compile with Flambo, I get a warning:

`Reflection warning, flambo/function.clj:28:21 - reference to field state can't be resolved.`

There doesn't seem to be a way to fix or suppress this, but CircleCI fails my build because of it. Is there any way to fix this?

**Comment by sorenmacbeth** [comment]
I removed the hard coded reflection warning. 

https://github.com/yieldbot/flambo/commit/d5a954cab8cf5d0b092a4b9dc3fedc94d6148658

I pushed a new 0.8.1-SNAPSHOT build with that change. I am planning an 0.8.1 release later this week as well.

**Comment by cigrainger** [comment]
Holy fast reply. Thanks a million! If there's anything I can do to contribute on the project let me know -- we're using Flambo pretty extensively for ETL work.

**Comment by sorenmacbeth** [comment]
awesome! glad to hear it. It case you didn't see, I released 0.8.1. If you are doing anything with streaming or dataframe/sql stuff in spark, those areas of flambo are less extensively used/covered so any contributions there would be cool.
