### ISSUE TITLE
Possible issue with set-if-missing?

### ISSUE THREAD

**Issue by MissingNo1028** [yieldbot/flambo#127]
(defn set-if-missing
  [conf key val]
  (.setIfMissing key val))

set-if-missing tries to call .setIfMissing on the key, which would be something like "spark.master". .setIfMissing tries to get called on the key string instead of the conf. It should probably be (.setIfMissing conf key val).

**Comment by sorenmacbeth** [comment]
Yep, I'll fix that, or you can submit a PR if you like

**Comment by leon-barrett** [comment]
Resolved by #128 .
