### ISSUE TITLE
[Query] Buffer Underflow in Kryo

### ISSUE THREAD

**Issue by kul** [yieldbot/flambo#46]
Hello @sorenmacbeth ,

I recently saw some kryo buffer underflow errors in some of my jobs with a slightly older build of my fork where your recent commits of chill upgrade were not there, with spark 1.2.0. But those disappeared with 0.5.0-SNAPSHOT. Did you also get this error? I was wondering what would be cause for it?

Please close this anytime as its not really an issue just a question.

Thanks

**Comment by sorenmacbeth** [comment]
Hi,

I've created a flambo-user google group for questions just like this. You can join it here:

https://groups.google.com/forum/#!forum/flambo-user

I'd encourage you to ask the question again there so the search history is available for others, and I can answer there as well.

**Comment by kul** [comment]
Thans @sorenmacbeth ,

Will close this.
