### ISSUE TITLE
ClassNotFoundException: flambo.function.Function

### ISSUE THREAD

**Issue by senor-hadoop** [yieldbot/flambo#52]
HW10964:spark-tutorial snunez$ lein deps
(Retrieving yieldbot/flambo/0.6.0-SNAPSHOT/flambo-0.6.0-20150408.182739-1.pom from clojars)
(Retrieving yieldbot/flambo/0.6.0-SNAPSHOT/flambo-0.6.0-20150408.182739-1.jar from clojars)

HW10964:spark-tutorial snunez$ lein repl
nREPL server started on port 59510 on host 127.0.0.1 - nrepl://127.0.0.1:59510
REPL-y 0.3.1
Clojure 1.6.0
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[flambo.api :as f])

CompilerException java.lang.ClassNotFoundException: flambo.function.Function, compiling:(flambo/function.clj:58:1)

**Comment by senor-hadoop** [comment]
Darn. I think this one bit me before. The answer is to ensure that :aot [flambo.function]} is in the :dev profile of project.clj. Perhaps this hint could make it into the Tutorial.md file for future users?

**Comment by sorenmacbeth** [comment]
Sure, we could do that. Closing this issu.
