### ISSUE TITLE
No matching method found for join

### ISSUE THREAD

**Issue by senor-hadoop** [yieldbot/flambo#53]
Walking through the tutorial, I get:

user=> (def tfidf-by-term (-> (f/join tf-by-doc idf-by-term)
  #_=>                               (f/map (f/fn [[term [[doc-id tf] idf]]]
  #_=>                                            [doc-id term (* tf idf)]))
  #_=>                               f/cache))

CompilerException java.lang.IllegalArgumentException: No matching method found: join for class org.apache.spark.api.java.JavaRDD, compiling:(form-init8987457259874014740.clj:1:24)

at the join step, the one with the heading TF-IDF.

I would love to see a version of the tutorial that users could walk through step by step. If it is any help, I've started modification of the existing tutorial (https://github.com/senor-hadoop/flambo/blob/develop/Tutorial.md) to pass along to others on my team.

**Comment by sorenmacbeth** [comment]
The tutorial is out of date for the changes in 0.5.0. I forgot to update it. We will do that. Thanks for catching this. I'll close this issue once it's been updated.

**Comment by senor-hadoop** [comment]
FYI, I’ve started rewriting the tutorial here. If you are open to pull-requests, you will probably have one tomorrow.

From: Soren Macbeth
Reply-To: yieldbot/flambo
Date: Wednesday, April 8, 2015 at 19:14
To: yieldbot/flambo
Cc: Steve Nunez
Subject: Re: [flambo] No matching method found for join (#53)


The tutorial is out of date for the changes in 0.5.0. I forgot to update it. We will do that. Thanks for catching this. I'll close this issue once it's been updated.

**Comment by sorenmacbeth** [comment]
Absolutely, that would be great. I'll wait for a PR from you.
