### ISSUE TITLE
Can't map in saveAsTextFile

### ISSUE THREAD

**Issue by afandian** [yieldbot/flambo#65]
Previously this worked:

    (.saveAsTextFile (f/map my-rdd pr-str) "filename")

I just upgraded to the latest and now I get the error:

    WARN fn: unable to call serializable.fn$serialize@6fc0bbc6
      on org.apache.spark.api.java.JavaSparkContext@29fe4840
      in {"output-location" "/Users/joe/sc/laskuri/example/hundred/output", "tasks" #{:doi-domain-periods-count :top-domains}, "doi-period-date" #<JavaPairRDD org.apache.spark.api.java.JavaPairRDD@25a1a012>, "doi-domain-period-date" #<JavaPairRDD org.apache.spark.api.java.JavaPairRDD@3c19592c>, "input-location" "/Users/joe/sc/laskuri/example/hundred/input/hundred.txt", "parsed-lines" #<JavaRDD MapPartitionsRDD[4]
      at filter at NativeMethodAccessorImpl.java:-2>, "period" :month, "ctx" #<JavaSparkContext org.apache.spark.api.java.JavaSparkContext@29fe4840>, "redact" false, "parsed-lines-period" #<JavaRDD MapPartitionsRDD[9]
      at map at NativeMethodAccessorImpl.java:-2>}

Should I expect this to continue to work? Is there another way to save lines of EDN serialised data in HDFS?

(Thanks for all your hard work!)

**Comment by sorenmacbeth** [comment]
That is just a WARNing, which you can ignore, unless you get some other ERROR later.
