### ISSUE TITLE
Using sparksql rows in flambo

### ISSUE THREAD

**Issue by ararog** [yieldbot/flambo#66]
Is sparksql row in flambo a map? I'm writting a function which parse a log line using regex and create a row based on match groups, these rows will be used in a set of RDDs for further processing.

Any hints?

**Comment by sorenmacbeth** [comment]
rows are Row object, there is a helper function here to turn those into vectors:

https://github.com/yieldbot/flambo/blob/develop/src/clojure/flambo/sql.clj#L123-L128

**Comment by ararog** [comment]
Let me try figure out how to instantiate it. Thanks!

**Comment by ararog** [comment]
One last thing, is the syntax something like:

(sql/Row {:host "value1" :client "value2"})

Because I'm getting:

No such var: sql/Row

Note: flambo.sql is already loaded as sql

**Comment by danoyoung** [comment]
@ararog did you get this working?  If so could you share some tips, running into similar issues...
