### ISSUE TITLE
How to create a comparator from api/fn macro?

### ISSUE THREAD

**Issue by ararog** [yieldbot/flambo#72]
I've been trying to create a compartor using f/fn macro and pass it to take-ordered to help me define a custom sorting approach.

```
(defn take-ordered
  "Return an array with the first n elements of `rdd`.
  (Note: this is currently not executed in parallel. Instead, the driver
  program computes all the elements)."
  [rdd cnt compare-fn]
  (.takeOrdered rdd cnt 
    (if (instance? Comparator compare-fn)
      compare-fn
      (comparator compare-fn)))) 
```

Here's what I have to far for take-ordered, I can pass compare to it, but I can't do something like 
(f/fn [v](* -1 %28get v 1%29)) where v in a vector or two elements [1 2] which is a element of other vector like [[1 2] [3 4] [5 6]]

**Comment by sorenmacbeth** [comment]
I'm assuming you sorted this out since your PR included take-ordered yes?

**Comment by ararog** [comment]
Not yet, so I believe I'll endup with something like (comparator (fn [x y] body)) or just (fn [x y] body), I think.
