### ISSUE TITLE
 WARN fn: caught exception: com.esotericsoftware.kryo.KryoException: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by danoyoung** [yieldbot/flambo#73]
I have a simple Flambo app that I'm working with that takes a text file of JSON objects/string (one per line) and does some simple snake casing of the keys, and then saves these back out as a Parquet file. When I add an anonymous fn (via (f/map (f/fn [x] ....) I get a Kyro warning....although the program runs, and is appearing to output the correct results, each time I add another anonymous fn to the threading operation, I get the same warning.  So a warning for each fn I add....

See:
https://www.refheap.com/3bf5a8f0cca762ca06010a78f

Is there something I should be doing differently and why am I getting these warnings?  If I remove all the (f/map ....) I get no warnings. I feel like I'm doing something knuckle headed here....

**Comment by danoyoung** [comment]
BTW, using Flambo 0.6.0 and Spark 1.3.1.....

**Comment by danoyoung** [comment]
Attached is a screen shot of where the exception is being thrown, it looks like in the best-effort-map-val fn.  Still digging around to understand why the exception is being thrown....I'm not sure if this is helpful or not....

<img width="1440" alt="screen shot 2015-07-08 at 2 09 56 pm" src="https://cloud.githubusercontent.com/assets/47937/8596569/65588fb6-260d-11e5-981c-fe383d01371d.png">

**Comment by sorenmacbeth** [comment]
Dan,

These are warnings when closure and params to your serializable functions couldn't be serialized by kryo (via serializable.fn). For the most part, you can ignore them unless you get an actual ERROR level exception later, in which case this WARN level exception might help you track down what happened.
