### ISSUE TITLE
defsparkfn does not support docstrings

### ISSUE THREAD

**Issue by b-ryan** [yieldbot/flambo#80]
I would have expected this to work:

```clj
(defsparkfn my-fn
  "Eats data and does cool stuff"
  [input]
  (...))
```

But I received an error that the first argument should be a vector.

**Comment by sorenmacbeth** [comment]
serialized function don't currently support doc strings. I'd be happy to take a PR on https://github.com/sorenmacbeth/serializable-fn to add them though.
