### ISSUE TITLE
How to destructure dataframe/rdd?

### ISSUE THREAD

**Issue by sihingkk** [yieldbot/flambo#84]
Hey, 

I have a bit more complex data structure which I'm loading from parquet:
```clojure
(def data (sql/parquet-file c (into-array ["/some-path/**"])))
(.printSchema data)
```

```
root
 |-- id: string (nullable = true)
 |-- modelVersion: string (nullable = true)
 |-- name: string (nullable = true)
...
```
is it possible somehow to destruct it?
something like:
```clojure
(def result (f/map data (f/fn [[ id _ name ]] (str id name))))
```

but I'm getting:
``` 
java.lang.UnsupportedOperationException: nth not supported on this type: GenericRowWithSchema
```

Is there any way to implement nth for GenericRowWithSchema?

**Comment by sorenmacbeth** [comment]
You could probably write a protocol and then extend the protocol to GenericRowWithSchema class, but in my experience this doesn't always work as expected and I usually just end up destructuring with `let` bindings
