### ISSUE TITLE
Cannot use map on RDD action result

### ISSUE THREAD

**Issue by minor6th** [yieldbot/flambo#98]
I tried the code below but got an error: 

> Exception in thread "main" java.lang.IllegalArgumentException: No matching method found: map for class scala.collection.convert.Wrappers$SeqWrapper

How can I iterate over the result from an RDD action?
```clojure
(def result
  (-> (f/text-file sc "filename")
      (f/map (f/fn [s] (first (str/split s #"\t"))))
      (f/take 10)))
(map println result))
```

**Comment by sorenmacbeth** [comment]
You have a typo in your `f/fn` inside of your `f/map`. there is a stray `first`.

**Comment by minor6th** [comment]
I have corrected the typo, but still got an error.

**Comment by sorenmacbeth** [comment]
I'll need a bunch more info:

What version of flambo are you using?
What version of spark are you using?
What does the code that creates your spark context `sc` look like?

The best thing to do is to paste you entire file as well as your project.clj.

**Comment by minor6th** [comment]
My entire file:
```clojure
 (ns zap.core
   (:require [flambo.conf :as conf]
             [flambo.api :as f]
             [clojure.string :as str])
   (:refer-clojure)
   (:gen-class))


 (defn -main []
   (def c (-> (conf/spark-conf)
              (conf/master "local")
              (conf/app-name "flame_princess")))

   (def sc (f/spark-context c))

   (def result
     (-> (f/text-file sc "filename") 
         (f/map (f/fn [s]
                  (first (str/split s #"\t"))))
         (f/take 10)))
   (f/map result println))
```
and my project.clj
```clojure
 (defproject zap "0.1.0-SNAPSHOT"
   :description "FIXME: write description"
   :url "http://example.com/FIXME"
   :main zap.core
   :auto-clean false
   :license {:name "Eclipse Public License"
             :url "http://www.eclipse.org/legal/epl-v10.html"}
   :dependencies [[org.clojure/clojure "1.8.0"]
                  [yieldbot/flambo "0.7.2"]]
   :profiles {:provided {:dependencies
                         [[org.apache.spark/spark-core_2.10 "1.6.1"]]}
              :uberjar {:aot :all}
              :dev {:aot [zap.core]}})
```

**Comment by sorenmacbeth** [comment]
`f/take` causes the RDD to be sent to the driver as a java collection. you should first convert it to a clojure collection, then use normal clojure functions on it. so the last line of your file should look like:

```clojure
(map println (vec result))
```

**Comment by minor6th** [comment]
I tried ``(map println (vec result))`` and got no output, 
but ``(println (vec result))1`` print out the clojure vector.

I also tried ``(println (map first (vec result)))``, this also produces the correct result.

It seems that ``map`` and ``println`` cannot be used together in this context.

**Comment by sorenmacbeth** [comment]
great, I'm going to close this issue then.

**Comment by minor6th** [comment]
OK, I finally find out the reason why ``(map println (vec result))`` has no output.
Because map is lazy so I have to use ``dorun`` to force the evaluation.
